
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Gestion_Contact
      POSTGRES_USER: Mon_utilisateur
      POSTGRES_PASSWORD: kramo
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
