services:

  db:
    image: postgres:latest
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: Mon_utilisateur 
      POSTGRES_PASSWORD: kramo 
      POSTGRES_DB: Gestion_Contact  

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8087:8087
     
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    
volumes:
  postgres_data: